apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels:
    app: frontend
    name: app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app-v2
      app: frontend
  template:
    metadata:
      name: app-v2
      labels:
        name: app-v2
        app: frontend
    spec:
      containers:
        - name : app-v2
          image: appcolor:v1
          env:
            - name: APP_COLOR
              value: green
            - name: APP_CONTENT
              value: "Hello World v2"
          ports:
            - containerPort: 80