---
apiVersion: v1
kind: Namespace
metadata:
  name: app-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: myapp-deploy
    app: frontend
  name: myapp
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp-pod
      app: frontend
  template:
    metadata:
      labels:
        name: myapp-pod
        app: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80

