apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  labels:
    name: webapp-svc
    app: service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: java
    name: webapp