apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-service
  name: app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    name: app-secrets-pod
    app: python
