apiVersion: v1
kind: Namespace
metadata:
  name: java-tuning
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-tuning
  namespace: java-tuning
  labels:
    app.kubernetes.io/name: java-tuning
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-tuning
  template:
    metadata:
      name: java-tuning
      namespace: java-tuning
      labels:
        app.kubernetes.io/name: java-tuning
    spec:
      containers:
        - name: java-tuning
          image: java-tuning:v1
          ports:
            - containerPort: 8888
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:ActiveProcessorCount=2 -XX:MaxRAMPercentage=75"
            - name: JAVA_OPTS
              value: "-server"
          resources:
            requests:
              memory: 1024M
              cpu: 1000m
            limits:
              memory: 1024M
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health
---
apiVersion: v1
kind: Service
metadata:
  name: java-tuning-svc
  namespace: java-tuning
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: java-tuning
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888