apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: mysc
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
