apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
  labels:
    app: test
spec:
  initContainers:
    - name: first-init
      image: busybox
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "echo \"sleeping for 20s\" && sleep 20"
    - name: second-init
      image: busybox
      command: ["/bin/sh"]
      args:
        - "echo \"sleeping for 10s\" && sleep 10 && echo \"Finish sleep...\""
  containers:
    - name: nginx-container
      image: nginx