apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-alpine-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myapp-alpine
  template:
    metadata:
      labels:
        app: myapp-alpine
    spec:
      containers:
      - name: myapp
        image: alpine
        command:
          - "sleep"
          - "3200"
