apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - controlplane
  containers:
  - name: secret
    command:
      - "sleep"
      - "3600"
    image: busybox
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
