apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  namespace: default
  labels:
    app: logs
spec:
  volumes:
    - name: my-volume
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /logs/
          name: my-volume
      ports:
        - containerPort: 80
    - name: kibana-logs
      image: elastic/kibana:8.7.0
      volumeMounts:
        - mountPath: /var/log/event-simulator/
          name: my-volume
      ports:
        - containerPort: 5601
