apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
spec:
  type: NodePort
  selector:
    app: logs
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
    nodePort: 30000
  - name: kibana-port
    port: 5601
    targetPort: 5601
    nodePort: 30001

