apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: myapp-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: myapp-nginx
