apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-log
  namespace: default
spec:
  storageClassName: ""
  claimRef:
    name: pvc-log
    namespace: default
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/pv/logs
