apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
spec:
  containers:
    - name: time-check
      image: busybox
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      command:
        - "sh"
        - "-c"
        - "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log"
      volumeMounts:
        - name: my-volume
          mountPath: /opt/time
  volumes:
    - name: my-volume
      emptyDir: {}