apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  hostPath:
    path:  /run/desktop/mnt/host/c/opt/volume/nginx # Windows Docker-Desktop: C:\opt\volume\nginx
    # path:  /opt/volume/nginx # Linux