apiVersion: v1
kind: Pod
metadata:
  name: my-pod-running
spec:
  tolerations:
    - key: "app"
      value: "MyTaint"
      operator: Equal
      effect: NoSchedule
  containers:
    - name: my-pod
      image: nginx
