apiVersion: v1
kind: Pod
metadata:
  name: socket-test-second-pod
  labels:
    name: socket-test-second-pod
    app: java
spec:
  containers:
    - name: socket-test-second-pod
      image: socket-test:v1
      ports:
        - containerPort: 8080
      env:
        - name: SERVER_NAME
          value: "second-pod"
        - name: POD_URL
          value: "http://kubernetes.docker.internal:30001"
