apiVersion: v1
kind: Pod
metadata:
  name: psql
  labels:
    app: db
    name: psql
spec:
  containers:
    - name: psql
      image: psql-custom:v1
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: app-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: app-secrets
        - name: POSTGRES_DB
          value: kubernetes
      ports:
        - containerPort: 5432
