apiVersion: v1
kind: Pod
metadata:
  name: app-jdbc
spec:
  containers:
    - name: app-jdbc
      image: app-jdbc:v1
      resources:
        limits:
          memory: "100Mi"
          cpu: "1000m"
        requests:
          memory: "100Mi"
          cpu: "1000m"
      env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              key: POSTGRES_URL
              name: app-secrets
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: app-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: app-secrets
        - name: TIMEOUT
          value: "2500"
        - name: RUNS
          value: "2"
