apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcHNxbC1zdmM6NTQzMi9rdWJlcm5ldGVz
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXMwNjYyNTI=
