apiVersion: v1
kind: Service
metadata:
  name: psql-svc
  labels:
    app: service
    name: psql-svc
spec:
  type: ClusterIP
  selector:
    app: db
    name: psql
  ports:
    - port: 5432
      targetPort: 5432