CREATE TABLE USUARIOS (
	ID SERIAL not null,
	NOME VARCHAR(255) not NULL
);

INSERT INTO USUARIOS (NOME) values ('USER');
INSERT INTO USUARIOS (NOME) values ('ADMIN');
INSERT INTO USUARIOS (NOME) values ('SUSER');

SELECT * FROM USUARIOS;